sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "dSAhes4XbRi7YTrGgILztF7QNI3hVik2buaMKYBo9gkfNg+1bPxjdGSunXti2FuAm7ic5YSNqHy6mixE7chbIFQl5f0oDDm8kbRU8kAzjucvO0B9M/hbC6MwZuO9+y3QlWbUFrIDQtDK19LOr+xSeXcvFhDuBeFjKnIu6vuvalfaNUIihDQvUe3tJo4YO0EMc9HB7S3l+Os9vMQJTNHR1tt0y9bJkMJqFivVJjnso0H/jUS8g4t0hkmxVjS9OST/OBmzULK3bJ0L7uyd8dbG/YaV0pcjxuhVNoexbdwrCND1EdT4IjvluTPP5x+SU8A5lb6tMwYgPUCeIDAKGFSzxysNguzYXNo6DNHo+zvAUvqgCVzzHs+wbA98YDRdCL4eDKt6AMjKuesrwGiRQM1fY1aPBzxbWCM2Uc4Q3K+rRFM3tgLC49FzYUOjNApnLLa5HQZuhm2wSr45I0rAM4HwVwmS91GC4ujRlnE0SIu7XvSkBWnpRZtWPAJSm9m8Hr1av4fBjKrf4ACKvkyjJPolH6MzEfIJwZbB+M6dPR0vdJ1IlVky7yqpNTCtRH1EdI/yCwTnIV/pIVsY9cJ7jk54Ht9yqrv0gNLeHQvua5lXN8zZdwez7oGCmhUx7qN5Hs/7VidFpOopsleMsWYu26RiUjXaw6kuIxj3yMKyuHX1SRk="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "VVjLpq0GzXJKDMsokAX9Ukciqv30Bs1p6HCWDqdbtL4EbeFXH4DE96Mi9Ve+LF6ccK8ddh20oAWc1taZlgwSFOf1yIB3Q0GyOWLErvpdxO0gA60UGdbHwfctXEk+zdHKUI5heVF+5kTf8/tHhOr7SKcjz+TP2VW86Mdc8CxmLrKxGIQcXZxUaQdndklb0qWD9MJanU0ihaLvAU/XLpRlbITSMkROrP5YYmN4sb/nEiut2Ae2Lv0zyrlTReBWc/ldxWCwSaz/z7N88NORR9EzTX+gzEGn+HDKlHfXDgNgVf0zaetM6rw5g92KQWMT6YxLn8TSQGR2TIGpfRpH0kTaY70h+P8vZAcTv+SkzbadU2A9YAcJuU+xki8yoL5lUZJ5Sh+0UHKPzqmiwsPTkSGYOtGf2Yq3v7jU7o3jc1cMDvjkAe/a0Ot0qhGiAxRd1FIjnvZacOWPAZ2UhTtdDkOg1AsOchRbV83Lh/gZtVLMIp0CdrKUML/RQuCwJVXu7rufE7djx28Tw562xWJXfcGQky9Jb2TpJh4jwCC2DGFWl/LOIih78wlKPMDo+V7TVxcnUlNlqfDtg9CpcEb6gyP6LTNxPgNIogjhrCWI65mGOhcOnCZgX1HNeUlm+24nst+ugE0IMJbUK23W+aXjitqOfzONWy6Gx9t9m8POxxqoXwI="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "KUDBwlA9qzCZlW3GkcXdcrUvouxYPUu1dOg9/C9J08YnYq6SKDJJLdCWOg3iCGeWQ54GDhReCBcPEbgslHnlKBHloDkpL6cxu5jNnZZhsC3VTpGYv1w7xm135BwhY6RouCfa0zoz/2sgU3LJQGVUQo9c11sgvPC7Exq6T/FrF+sT7Djc06EwOt6WcFLI7e0TidiWwBJxfUb+rQPYdmuDhTn2jQJKuuxPBa4UkSG/KPBe51HvnsJfA4rme2VdUIZt0F8NHj6zR6jY2zSf+fV6jvCSXm9SLWwEJnjBi3oOG8vKSAoD2f/c1aX2Bv8sXcSf4HXz0WFc+UMHhsvx/SuURvyRysKosIG2sYCUa78GEI5iNfDX2zBNmW05AfZOGc/Szic2Oq/t/A0Nk3vqTZI9n0qkLfPONgCrX1g8JUq8P4xZprVz4yz/falsg1B3RW7Bpjdahqa7XvS4j9G0LRn0h9gP4f6Yl74sKVmkSaPIAEJLIsLqUT7b/DtV+VAYmjV7r6qqDiBYxF4Bbb8pz0zjj7SRGPYP9mobQvOJsXz+DKytFKf/QqoLsvDFedIPPiLXnzICkzmq4WOmDu/A+thgrokpeQ8/acB8muvtw6iqAFPLqeydyrH3Y33e0XJVIkzxPU/Pmzh6FGLpus0bp+cakFP6EGQkAwFuO8k/0kT1Ye8="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "wiVXMjXD484eKFxler1Leu63kDGDuNBfFgqlMYb0LyT7pUnwNypIRqi4/S4p7FyMsy982TMEm2Vg56MN4yrDSZ/NnY4eb7g16dOXlIqaLkytJSAtylhD+f0NCD3rp0PoiBA2YeSwlmFyqSOCdzPnqFqqHEG2kMOgLpc5Qt4sID+cujIQn14H4zikyduihT10ivdmv/2jNVD7DvoJx4KiaOEt4FKUWls//TGUz9NgEDlqTeHqQQ2Yv0rlzzm0RwyTO3U1o2Ua0bVKCetAsptAsGK1gz0xMizhOGpc0olet/AR1eN6XmPixjL8KS12nCySGnBv/1ugXhSLdmifuToMBXMjYqLRIownN99NiVMT2DPVDo3Bwes4OKD5ZFVJskJZEJwlWoNzX25YZ/hDyXoiGuAUpJyyntFeGT7QsRv2XbfCy2bxxn6S6E4wtVcTgRDAHQvEiXOq3+qJFOfiae7DbStYJSUqAawJrt8p+50Agd1+r+fyBVbJ5xvD8G0xFVyHroJgM1YJQFwPCthsIrwXxtHQMuby5EXDHI8UcQ9yvb8D/AvytB/kT/F7k7E0OLEzM0BvQ+Pl3GBJJMOq1ydsWiZ+fb+KRUZf1tTTfY/mwDeRmMPkFAHobKy0sENh+GdwcB2z29RAeNS573pl5pq06ehVoqfQfY+aqs6XrAP2kFc="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "kgaNRDKsM9uzerO7aSiuW2CNQq+0p2WDiQ5Iy5fCOl8sBOiA2em22aa0nj4/2PmGc22OvBMFeKtJy3D53oYl4cLBimGDFg+vYm1BI/TrdD2dKPpP1KqnetZWNIF7LLdezba+rnLt2R2SZ4uxxrMB+9+wOCBDCqAl0k7D1XMuKJBl3u9KPOPxcEgGXWnijoMxe8jkoRnl+hGN8GvIkb3EtrIl3GlSYwWjpTYZ9ojuLrXjlaJy4Q+098worb8gtQFRMpZDc7WLJFqy1ENNGt/9+S5P5sPpGJbfM6aVbyO8A2Yl6+iwdBumPPRMJbPmPWrbwFxSUhZqqMgBWl9Ok4AlzOHxM6rl752EU6IXCQFn+fZ+XLYLDBbB5IuYAKhT60oIUUnBpRJy7BnU71tI6Hf0aXYC1fQACZNal7he16GiehLaLrBQcLArJp/JwO7q6fuv6ovplL++cUddKhp5daZTHh8Uwi1Emi+nUISpEnhYuswWUHwyhl79bXm+fAbTOOKmNnQ+iw2t3pTqyNwQRnIJCznshQlILz9LO4siJGyX87SGzUEWnGsRU2ECQkLDKpCGCJMez8vTmZlTOUAKv12T6dVM9Eq7u/j023Mrx+EsLYgsgu4sV+R3IHpA0I4pTbFfstu7TEz55taTLSRerEYmnrAOp8zzfOnPRn8qxitLTro="
